#!/bin/bash

in_xdr=0
in_f90=0
f90_libs='-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_def -lpthread'
#f90_libs=-llapack
f90_flags='-fast'
#f90_opts='-check all'


if [ ! -d xdrfiles ]; then

   in_xdr=1
   echo ' '
   echo '>>>>>> Installing the xdr libraries...'
   echo '>>>>>> Installing the xdr libraries...' > INSTALL.log
   tar -zxvf xdrfile-1.1.1.tar.gz 1>/dev/null
   cd xdrfile-1.1.1/
   ./configure --prefix=$PWD/../xdrfiles --enable-fortran F77=ifort --enable-shared 1>> ../INSTALL.log 2>> ../INSTALL.log
   make install 1>> ../INSTALL.log 2>> ../INSTALL.log
   make test >> ../INSTALL.log 2>> ../INSTALL.log
   cd ..
   rm -r xdrfile-1.1.1
   cd xdrfiles
   path_xdr=$PWD
   cd ..
   awk '{if ($1=="path_lib_xdr") $3="\"'$path_xdr'\""; print $0}' pynoramix.py > pynoramix.py_new
   mv pynoramix.py_new pynoramix.py

   check=0
   grep 'Testing basic xdrfile library: PASSED' INSTALL.log 1>/dev/null
   check=$[$?+$check]
   grep 'Testing xtc functionality: PASSED' INSTALL.log 1>/dev/null
   check=$[$?+$check]
   grep 'Testing trr functionality: PASSED' INSTALL.log 1>/dev/null
   check=$[$?+$check]
   if [ $check -eq 0 ]; then
      echo '> XDR libraries compiled in '$path_xdr
      echo '> Update the LD_LIBRARY_PATH with the addition of:'
      echo '>' $path_xdr'/lib/'
   else
      echo '> Error: check the file INSTALL.log'
   fi
   echo ' '

fi

f_files=(pyn_water.f90 pyn_fort_enm.f90 pyn_fort_general.f90 pyn_fort_net.f90 pyn_hbonds.f90)


for ff in ${f_files[*]}; do
    if [ ! -e ${ff%.*}.so ]; then
	in_f90=1
    fi
done

if [ $in_f90 -eq 1 ]; then
    echo ' '
    echo '>>>>>> Compiling the fortran libraries...'
    if [ $in_xdr -eq 1 ]; then
	echo '>>>>>> Compiling the fortran libraries...' >> INSTALL.log
    else
	echo '>>>>>> Compiling the fortran libraries...' > INSTALL.log
    fi
fi

for ff in ${f_files[*]}; do
    if [ ! -e ${ff%.*}.so ]; then
	f2py --f90flags=$f90_flags -c -m ${ff%.*} $ff $f90_libs 1>> INSTALL.log 2>> INSTALL.log
	if [ ! -e ${ff%.*}.so ]; then
	    echo '> Error compiling' $ff': check the file INSTALL.log'
	else
	    echo '>' ${ff%.*}.so 'compiled.'
	fi
    fi
done

if [ $in_f90 -eq 1 ]; then
    echo ' '
fi


